version: "3"

services:
  node: 
    build: .
    container_name: "spellbook_api"
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      API_PORT: 3001
      NODE_ENV: 'development'
    networks:
      - spellbook-network

  db:
    container_name: "spellbook_db"
    image: mysql:8.0.23
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - spellbook-network

networks:
  spellbook-network:
    driver: bridge
